Корпоративный Закон в игре
space-sunrise/sunrise-station pull request #558
Opened 2024-10-28 20:16 UTC by AverageNotDoingAnythingEnjoyer

## Кратное описание

Resolves #502 
Данный PR портирует корпоративный закон во всём его водяном величии в игру
На данный момент нужно:
- [] Доработать вступление, уточнить некоторые моменты у викиделов, в частности требования для установки трекера
- [] Добавить раздел модификаторов
- [] Добавить раздел ОПРС
- [X] Добавить раздел статей и пояснений к ним (на данный момент ломает игру)
- [] Разобраться с причинами вылетов клиента 

## По какой причине

Описаны в #502 

## Медиа(Видео/Скриншоты)

На данный момент нет

## Проверки

- [ ] Я не требую помощи для завершения PR
- [ ] Перед выкладыванием/запросом о рассмотрении PR, Я проверил работоспособность изменений.
- [ ] Я добавил скриншоты/видео изменений, или данный PR не меняет внутриигровые механики

**Changelog**

:cl: J C Denton
- add: TBD
- remove: TBD
- tweak: TBD
- fix: TBD

2024-10-29 08:44 UTC, Rinary1 commented
Resolves #530

2024-10-30 10:24 UTC, Rinary1 requested changes
пу-пу-пу

2024-10-30 10:24 UTC, Rinary1 commented on Resources/ServerInfo/Guidebook/ServerRules/SpaceLaw/SpaceLaw.xml
>  </Document>
????

2024-10-30 10:24 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Guidebook/rules.yml
> +  priority: 5
```suggestion
  priority: 2
```

2024-10-30 10:24 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Guidebook/rules.yml
> +  priority: 5
```suggestion
  priority: 3
```

2024-10-30 10:24 UTC, Rinary1 commented on Resources/Prototypes/_Sunrise/Guidebook/rules.yml
> +  priority: 5
```suggestion
  priority: 4
```

2024-10-30 10:26 UTC, AverageNotDoingAnythingEnjoyer commented on Resources/ServerInfo/Guidebook/ServerRules/SpaceLaw/SpaceLaw.xml
>  </Document>
Вынес в отдельный файл перевод чтобы не было конфликтов, когда визы будут менять кз

2024-11-19 17:12 UTC, pxc1984 commented
Это надо 👍

2025-02-01 12:31 UTC, disssr commented
и че тут так долго делать

2025-03-25 06:58 UTC, VigersRay commented
деад пр

2025-04-01 21:12 UTC, Francus41 commented
деад пр

2025-04-16 16:53 UTC, KaiserMaus commented
Упал-вставай, конфликт-решай насрали-закрывай

2025-04-16 16:53 UTC, closed without merging